FROM continuumio/miniconda3
ADD . /code
WORKDIR /code
RUN conda update -y conda 
RUN conda install -y -c anaconda numpy flask gunicorn gevent
RUN conda install -y -c conda-forge flask-socketio python-confluent-kafka
RUN mkdir -p /home/barnwaldo
COPY epd.conf /home/barnwaldo/
